import { z } from 'zod';

export const EventDomainSchema = z.enum([
  'inventory',
  'location',
  'task',
  'equipment',
  'robotics',
  'manufacturing',
  'quality',
  'maintenance',
  'sensor',
  'container',
  'shipment',
  'order_fulfillment',
  'system',
]);

export type EventDomain = z.infer<typeof EventDomainSchema>;

export const EVENT_TYPES = [
  'inventory.movement.reported',
  'inventory.quantity.observed',
  'inventory.pick.completed',
  'inventory.putaway.completed',
  'inventory.replenishment.completed',
  'inventory.cycle_count.completed',
  'inventory.exception.reported',
  'location.status.changed',
  'task.created',
  'task.started',
  'task.completed',
  'task.failed',
  'task.cancelled',
  'equipment.status.changed',
  'equipment.alarm.raised',
  'equipment.alarm.cleared',
  'robotics.mission.started',
  'robotics.mission.completed',
  'robotics.mission.failed',
  'manufacturing.work_order.started',
  'manufacturing.production.completed',
  'manufacturing.scrap.reported',
  'quality.inspection.completed',
  'maintenance.issue.reported',
  'sensor.reading.observed',
  'container.scanned',
  'container.moved',
  'shipment.loaded',
  'shipment.received',
  'order_fulfillment.pick_completed',
  'system.heartbeat',
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

export const EventTypeSchema = z.enum(EVENT_TYPES);

export const DOMAIN_BY_EVENT_TYPE: Record<EventType, EventDomain> = {
  'inventory.movement.reported': 'inventory',
  'inventory.quantity.observed': 'inventory',
  'inventory.pick.completed': 'inventory',
  'inventory.putaway.completed': 'inventory',
  'inventory.replenishment.completed': 'inventory',
  'inventory.cycle_count.completed': 'inventory',
  'inventory.exception.reported': 'inventory',
  'location.status.changed': 'location',
  'task.created': 'task',
  'task.started': 'task',
  'task.completed': 'task',
  'task.failed': 'task',
  'task.cancelled': 'task',
  'equipment.status.changed': 'equipment',
  'equipment.alarm.raised': 'equipment',
  'equipment.alarm.cleared': 'equipment',
  'robotics.mission.started': 'robotics',
  'robotics.mission.completed': 'robotics',
  'robotics.mission.failed': 'robotics',
  'manufacturing.work_order.started': 'manufacturing',
  'manufacturing.production.completed': 'manufacturing',
  'manufacturing.scrap.reported': 'manufacturing',
  'quality.inspection.completed': 'quality',
  'maintenance.issue.reported': 'maintenance',
  'sensor.reading.observed': 'sensor',
  'container.scanned': 'container',
  'container.moved': 'container',
  'shipment.loaded': 'shipment',
  'shipment.received': 'shipment',
  'order_fulfillment.pick_completed': 'order_fulfillment',
  'system.heartbeat': 'system',
};
