packages:
  - 'apps/*'
  - 'packages/*'
  - 'connectors/*'
  - 'destinations/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@node-rs/argon2': true
  esbuild: true
  prisma: true
